# Generated by Django 5.0 on 2023-12-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='investments',
            name='frequency_type',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('monthly', 'monthly'), ('quaterly', 'quaterly')], max_length=50, null=True),
        ),
    ]
