# Generated by Django 5.0 on 2023-12-21 17:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_investments_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='reciept',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
