# Generated by Django 5.0 on 2023-12-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_investments_reciept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investments',
            old_name='reciept',
            new_name='image',
        ),
    ]
