# Generated by Django 5.0 on 2023-12-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investments',
            name='document',
        ),
        migrations.AddField(
            model_name='investments',
            name='document_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
