# Generated by Django 5.0 on 2024-01-31 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_investments_document_investments_document_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
