# Generated by Django 5.0 on 2024-02-02 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_profile_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_withdraw',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(blank=True, max_length=40, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=300, null=True)),
                ('bank_number', models.CharField(blank=True, max_length=300, null=True)),
                ('bank_address', models.CharField(blank=True, max_length=300, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('confirmed', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
