# Generated by Django 5.0 on 2024-02-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_profile_can_withdraw_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='acc_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
